data <- read.table("~/Desktop/COURSERA/Exploratory Data Analysis/household_power_consumption.txt", header = T, sep = ";", na.strings = "?")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data <- subset(data, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
data$datetime <- strptime(paste(data$Date, data$Time), "%Y-%m-%d %H:%M:%S")
data$Global_active_power <- as.numeric(data$Global_active_power)
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
dev.copy(png, file = "plot4.png", height = 480, width = 480)
dev.off()
par(mfrow = c(2,2))
hist(data$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col = "Red")
plot(data$datetime,data$Global_active_power, type = "l", xlab = "datetime", ylab = "Global Active Power (kilowatts)")
plot(data$datetime,data$Sub_metering_1,type = "l", ylab = "Energy sub metering",xlab= "")
lines(data$datetime,data$Sub_metering_2,type = "l",col="red")
lines(data$datetime,data$Sub_metering_3,type = "l",col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),cex=0.2,inset = 0)
plot(data$datetime,data$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
